name: samba

services:
  samba:
    image: crazymax/samba
    container_name: samba
    network_mode: internet
    hostname: portainer
    environment:
      - TZ=Asia/Makassar
      - SAMBA_LOG_LEVEL=0
    volumes:
      - ./data:/data
      - ./config/config.yml:/data/config.yml
      - /Users/aditya:/samba/data
    ports:
      - 445:445
    restart: always