name: portainer

services:
  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    network_mode: internet
    hostname: portainer
    environment:
      - TZ=Asia/Makassar
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    ports:
      - 9000:9000
    restart: unless-stopped